AllCops:
  DisabledByDefault: true
  DisplayCopNames: true

# Layout

Layout/AlignArray:
  Enabled: true

Layout/AlignHash:
  Enabled: true

Layout/AlignParameters:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/DotPosition:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/FirstParameterIndentation:
  Enabled: true

Layout/IndentArray:
  Enabled: true

Layout/IndentAssignment:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/IndentHash:
  Enabled: true

Layout/InitialIndentation:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true

Layout/SpaceAfterNot:
  Enabled: true

Layout/SpaceAroundBlockParameters:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/SpaceInsideRangeLiteral:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  Enabled: true

Layout/Tab:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/SpaceInsideBrackets:
  Enabled: true

# Lint

Lint/AssignmentInCondition:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/BlockAlignment:
  Enabled: true

Lint/CircularArgumentReference:
  Enabled: true

Lint/ConditionPosition:
  Enabled: true

Lint/DefEndAlignment:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateCaseCondition:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicatedKey:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyExpression:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EmptyWhen:
  Enabled: true

Lint/EndAlignment:
  Enabled: true

Lint/EndInMethod:
  Enabled: true

Lint/FloatOutOfRange:
  Enabled: true

Lint/FormatParameterMismatch:
  Enabled: true

Lint/ImplicitStringConcatenation:
  Enabled: true

Lint/IneffectiveAccessModifier:
  Enabled: true

Lint/LiteralInCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/MultipleCompare:
  Enabled: true

Lint/NestedMethodDefinition:
  Enabled: true

Lint/NextWithoutAccumulator:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/StringConversionInInterpolation:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnneededSplatExpansion:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/UselessComparison:
  Enabled: true

Lint/UselessSetterCall:
  Enabled: true

Lint/Void:
  Enabled: true

# Style

Style/AccessorMethodName:
  Enabled: false 

Style/AsciiIdentifiers:
  Enabled: true

Style/ClassAndModuleCamelCase:
  Enabled: true

Style/ConstantName:
  Enabled: true

Style/MethodName:
  Enabled: true

Style/PredicateName:
  Enabled: true

Style/VariableName:
  Enabled: true

Style/VariableNumber:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/AsciiComments:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/EachForSimpleLoop:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/EmptyMethod:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/For:
  Enabled: true

Style/IdenticalConditionalBranches:
  Enabled: true

Style/IfInsideElse:
  Enabled: true

Style/InfiniteLoop:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/MultipleComparison:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NestedModifier:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/NonNilCheck:
  Enabled: true

Style/OptionalArguments:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Style/TrailingCommaInLiteral:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/UnneededInterpolation:
  Enabled: true

Style/WhenThen:
  Enabled: true

Style/YodaCondition:
  Enabled: true

Style/ZeroLengthPredicate:
  Enabled: true
