# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e9db73fc2513db2c1b9cda05edfb6c88c3d9d5c0da508d3a1200782f7b776650986b5ae8b27ea80c17589650ae41150b93e8d9f36aa01256e6783f6d71b5d62

test:
  secret_key_base: b9300fb871c61a7b8612220917c857d7e8f6fabb235711d27304cee098c71dc2050436ce89fb1ded16413378c928633956afa0baf4d834cf33a7ed95195ba00f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
